namespace: production
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress.yaml
commonLabels:
  app.kubernetes.io/name: altjservice
images:
- name: gcr.io/personalsdm-216019/altjserver
  newTag: v118
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
decryption:
  provider: sops
  secretRef:
    name: sops-gpg
